stages:
  - get 
  - build


image: msnook/ansible-packer-terraform

variables:
  PACKER_DIR: packer
  TF_DIR: terraform
  PLAN: plan.tfplan
  S3_BUCKET: terraform-remote-state-def

get_packer:
  stage: get
  script:
    - echo -n "Fetching packer"
    - cd terraform
    - terraform init

build_ami:
  stage: build
  script:
    - echo "Build AMI"
    - cd packer 
    - packer build template_ami.json 2>&1 |  tee output.txt
    - AMI_ID=$(tail -2 output.txt |head -2 | awk 'match($0, /ami-.*/) { print substr($0, RSTART, RLENGTH) }')
    - echo $AMI_ID
  when: manual
  only:
    - master